# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: Java CI (JDK 17)

# Trigger on push or pull_request to 'this' branch, where 'this' is whichever branch this action exists on. 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Setup Java JDK
      uses: actions/setup-java@v5.4.0
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        architecture: x64
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5.1
      with:
        maven-version: 3.9.16
    - name: Maven Version
      run: mvn --version
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
    - name: Upload jar artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: ukf-members-snapshot
        path: target/ukf-members*.jar
        retention-days: 90
